version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ui:/var/www/app
    restart: always
    networks:
      - app
  app:
    build: api
    env_file: ".env"
    depends_on:
      - mongo
    networks:
      - app
    restart: always
  mongo:
    image: mongo:5.0
    ports:
      - "1488:27017"
    env_file: ".env"
    volumes:
      - ./.mongo:/data/db
    networks:
      - app
    restart: always
networks:
  app:
    driver: bridge
